### ISSUE TITLE
Request: package the project and publish to the Python Package Index

### ISSUE THREAD

**Issue by ropable** [realiii/pygeopkg#1]
I've found this project to be extremely useful in several projects that I maintain for my organisation. At present I generally use pygeopkg in those projects by adding it as a Git submodule; however it seems like it would be relatively straightforward to package and publish it to Pypi (I note that the `pygeopkg` namespace is unused).

Is this something that the maintainers would be interested in, or alternatively something that would be welcomed as a pull request? I'd be happy to do so, having packaged a couple of other simple projects in the past.

**Comment by jlhumber** [comment]
Thanks for the feedback, glad it has been of use.  Agreed, would be nice to have this `pip` installable.  It is probably enough just to make it installable via `pip install git+https://github.com/realiii/pygeopkg`.  Definitely open to a PR ... and now you've reminded me that this repo needs a little bit of modernization.

**Comment by ropable** [comment]
PR #2 submitted

**Comment by jlhumber** [comment]
pushed to pypi
