### ISSUE TITLE
Add gpkg_ogr_contents table with feature count

### ISSUE THREAD

**Issue by Rikuoja** [realiii/pygeopkg#5]
Currently, the generated geopackage does not contain feature counts in the gpkg_ogr_contents table (https://gdal.org/drivers/vector/gpkg.html#dataset-creation-options).

This means that if we are writing to an existing geopackage generated with e.g. QGIS, the feature counts for layers will not be updated and QGIS will show old feature counts. Also, QGIS cannot correct this any more. Probably triggers that update feature counts in this table are also missing.

**Comment by jlhumber** [comment]
Thanks for pointing this out and for the link.  We'll take a look.

**Comment by jlhumber** [comment]
This has been added.  The table is created for the geopackage and triggers are added when feature class or table is created.  

FYI, you may be interested in [this project](https://github.com/realiii/fudgeo) too, it is python 3 only but a touch more modern than pygeopkg.
