### ISSUE TITLE
Tiles support?

### ISSUE THREAD

**Issue by securedimensions** [realiii/pygeopkg#7]
## Question: Is it planned to support GeoPackage Tiles in the near future?

Currently, I am writing two OGC draft GeoPackage extension standards. One for Features and one for Tiles. Milestone for RFC is September 2022. 

To generate GeoPackage instance files for compliance testing, I am looking for an easy to use library. Looking at this library, it looks promising for the Features extension. But, there is no Tiles support :-(

It would be great to see the Tiles support in the near future. Possible?

Best
Andreas

**Comment by jlhumber** [comment]
@securedimensions thanks for the inquiry.  We do not have plans at the moment for including tiles in `pygeopkg`, if someone wanted to contribute an implementation or provide guidance on an implementation then we would be open to that.  

Please note that [fudgeo](https://github.com/realiii/fudgeo) is where we are doing our recent GeoPackage work -- its a more modern and python 3.x only package.
