### ISSUE TITLE
Add support for MultiPolygonZ

### ISSUE THREAD

**Issue by disarticulate** [realiii/pygeopkg#8]
It looks like there's no Z space for polygons.

http://www.geopackage.org/spec131/#_sqlite_container

I can't see why it's left out of the standard types.

**Comment by jlhumber** [comment]
Hi Eric,

Thanks for connecting with us.  Please check out our modernized support for GeoPackage in [fudgeo](https://pypi.org/project/fudgeo/).  All the geometry types are there as well as support for most of the GeoPackage extensions (e.g. spatial index, metadata, schema).  We also rolled in quite a a few speed-ups for reading and writing.

Hope that helps!

Jason

**Comment by disarticulate** [comment]
cool. Might want to deprecate this library and point there.
